services:
  db:
    container_name: gteemax-db
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=gteemax
    volumes:
      - gteemax-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  gteemax-db: