spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: gteemax
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gteemax
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
gtee:
  video:
    dir: video