spring:
  application:
    name: gteemax
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gteemax
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
gtee:
  video-dir: video
debug: true
logging:
  level:
    web: trace